import xgboost as xgb
import m2cgen as m2c
import time
import re

print("\n--- PHASE 4: BRAIN EXTRACTION (THE ULTIMATE C++ WRAPPER) ---")
start_time = time.time()

print(" -> Loading AI Brain from JSON...")
model = xgb.XGBClassifier()
model.load_model("branch_predictor_brain.json")

# Prevents m2cgen from tripping over missing base_score metadata
model.base_score = 0.5 

print(" -> Transpiling to bare-metal C/C++...")
raw_c_code = m2c.export_to_c(model)

print(" -> Patching strict C++ memory violations...")
# Change the default generic name to a private internal inline function
cpp_code = raw_c_code.replace("void score(double * input, double * output)", "inline void _m2cgen_score(double * input, double * output)")

# Your C99 memcpy patch (Kept and formatted for strict C++)
cpp_code = re.sub(
    r"memcpy\(output, \(double\[\]\)\{(.*?), (.*?)\}, 2 \* sizeof\(double\)\);", 
    r"output[0] = \1;\n    output[1] = \2;", 
    cpp_code
)

print(" -> Building the Architectural Wrapper...")
# Inject a clean C++ wrapper class around the raw double arrays
header_content = f"""// AUTO-GENERATED BY XGBOOST TRANSPILER & M2CGEN
// ==================================================
// DO NOT EDIT MANUALLY - PHASE 4 AI PREDICTOR
// ==================================================
#ifndef AI_PREDICTOR_H
#define AI_PREDICTOR_H

#include <cstdint>

namespace AIPredictor {{

    // --- Raw Transpiled Decision Trees ---
{cpp_code}

    // --- The Clean Architectural Wrapper ---
    // Pass your 4 strict features here, and it returns 1 (Taken) or 0 (Not Taken)
    inline int predict(uint64_t pc, uint64_t target, int isBackward, uint8_t localHistory) {{
        
        // 1. Prepare the input array exactly as XGBoost expects (4 features)
        double input[4] = {{ 
            static_cast<double>(pc), 
            static_cast<double>(target), 
            static_cast<double>(isBackward), 
            static_cast<double>(localHistory) 
        }};
        
        // 2. Prepare the output array (m2cgen outputs Class 0 and Class 1 scores)
        double output[2] = {{0.0, 0.0}};
        
        // 3. Run the bare-metal decision trees
        _m2cgen_score(input, output);
        
        // 4. Return 1 (Taken) if Class 1 score > Class 0, else 0 (Not Taken)
        return (output[1] > output[0]) ? 1 : 0;
    }}

}} // namespace AIPredictor

#endif // AI_PREDICTOR_H
"""

print(" -> Writing ai_predictor.h...")
with open("ai_predictor.h", "w") as f:
    f.write(header_content)

print(f" -> Execution Time: {time.time() - start_time:.2f} seconds")
print("\n==========================================")
print("      EXTRACTION SUCCESSFUL & WRAPPED!      ")
print("==========================================\n")
