import xgboost as xgb
import m2cgen as m2c
import time
import re

print("\n--- PHASE 4: BRAIN EXTRACTION (PATCHED) ---")
start_time = time.time()

print(" -> Loading AI Brain from JSON...")
model = xgb.XGBClassifier()
model.load_model("branch_predictor_brain.json")
model.base_score = 0.5

print(" -> Transpiling to bare-metal C++...")
cpp_code = m2c.export_to_c(model)

print(" -> Patching C++ strict memory violations...")
# FIX 1: Update the correct function signature (taking an input AND an output array)
cpp_code = cpp_code.replace("void score(double * input, double * output)", "void predict_branch_ai(double * input, double * output)")

# FIX 2: Rewrite the illegal C99 temporary array into strict C++ assignments
cpp_code = re.sub(
    r"memcpy\(output, \(double\[\]\)\{(.*?), (.*?)\}, 2 \* sizeof\(double\)\);", 
    r"output[0] = \1;\n    output[1] = \2;", 
    cpp_code
)

print(" -> Writing C++ Header File...")
with open("ai_predictor.h", "w") as f:
    f.write("// AUTO-GENERATED BY XGBOOST TRANSPILER\n")
    f.write("// DO NOT EDIT MANUALLY\n\n")
    f.write(cpp_code)

end_time = time.time()
print("\n==========================================")
print("        EXTRACTION SUCCESSFUL!            ")
print("==========================================\n")